name: sync-repo-to-supabase

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.md"
      - "**.py"
      - "**.yml"
      - "**.yaml"
      - "**.sql"
      - "**.toml"
      - "**.json"
      - "**.txt"
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install supabase openai

      - name: Sync to Supabase (docs + embeddings)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          BRANCH: ${{ github.ref_name }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # ← 追加
        run: |
          python sync_repo_to_supabase.py
