name: sync-repo-to-supabase

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.md"
      - "**.py"
      - "**.yml"
      - "**.yaml"
      - "**.sql"
      - "**.toml"
      - "**.json"
      - "**.txt"
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install supabase

      - name: Sync to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          # サービスロールキー推奨（RLSバイパス・Actions専用）
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          # ブランチ名（手動実行時などの保険）
          BRANCH: ${{ github.ref_name }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python sync_repo_to_supabase.py
