create table if not exists public.daily_monitor_reports (
  id bigint generated by default as identity primary key,
  report_date date not null,
  strategy_name text not null,
  simulation_name text not null default '',
  latest_market_date date not null,
  open_positions_count integer not null default 0,
  entry_candidates_count integer not null default 0,
  blocked_signals_count integer not null default 0,
  report_markdown text not null,
  line_summary text null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_monitor_reports_unique unique (report_date, strategy_name, simulation_name)
);

create index if not exists idx_daily_monitor_reports_lookup
  on public.daily_monitor_reports (report_date desc, strategy_name, simulation_name);
