create table if not exists public.daily_trader_orders (
  id bigint generated by default as identity primary key,
  simulation_name text not null,
  ticker text not null references public.tickers(code),
  strategy_name text not null,
  param_set_id bigint null references public.strategy_param_sets(id),
  position_id bigint null references public.live_positions(id) on delete cascade,
  order_type text not null check (order_type in ('ENTRY', 'EXIT')),
  scheduled_for date not null,
  status text not null default 'PENDING' check (status in ('PENDING', 'EXECUTED', 'CANCELLED')),
  reason text null,
  signal_ts timestamptz null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_daily_trader_orders_lookup
  on public.daily_trader_orders (simulation_name, scheduled_for, status, ticker);
